# Generated by Django 5.0 on 2024-01-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_offrevoyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrevoyage',
            name='image',
            field=models.ImageField(default='img/justGo-logo-light.png', upload_to='voyages/'),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='number_of_people',
            field=models.IntegerField(default=0),
        ),
    ]
