# Generated by Django 5.0 on 2024-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_offrevoyage_image_offrevoyage_number_of_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offrevoyage',
            name='image',
            field=models.ImageField(default='img/justGo-logo-light.png', upload_to='static/img/'),
        ),
    ]
