# Generated by Django 5.0 on 2024-01-10 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_offrevoyage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrevoyage',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
