# Generated by Django 5.0 on 2024-01-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_offrevoyage_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offrevoyage',
            name='duration',
        ),
    ]
