# Generated by Django 5.0 on 2024-01-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_offrevoyage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrevoyage',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
