# Generated by Django 5.0 on 2024-01-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_offrevoyage_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrevoyage',
            name='activite_prevue',
            field=models.TextField(default='No activities planned'),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='compagnie_transport',
            field=models.CharField(default='Compagnie XYZ', max_length=255),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='genre',
            field=models.CharField(choices=[('Aventure', 'Aventure'), ('Culturel', 'Culturel'), ('Détente', 'Détente'), ('Sportif', 'Sportif')], default='Aventure', max_length=20),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='hebergement',
            field=models.CharField(default='Hôtel', max_length=255),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='speciale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='type_transport',
            field=models.CharField(default='Avion', max_length=255),
        ),
    ]
