# Generated by Django 5.0 on 2024-01-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_offrevoyage_activite_prevue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offrevoyage',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img/default_image.png', upload_to='static/img/')),
                ('offre_voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.offrevoyage')),
            ],
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='offres_voyage', to='blog.image'),
        ),
    ]
