# Generated by Django 5.0 on 2024-01-11 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_offrevoyage_image_image_offrevoyage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offrevoyage',
            name='images',
        ),
    ]
