# Generated by Django 5.0 on 2024-01-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_userprofile_age_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='img/default_image.png', upload_to='site_images/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_images/profile.jpg', upload_to='profile_images/'),
        ),
    ]
