# Generated by Django 5.0 on 2024-01-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_image_image_alter_userprofile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='offrevoyage',
            name='countries',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='offrevoyage',
            name='genre',
            field=models.CharField(choices=[('Aventure', 'Aventure'), ('Culturel', 'Culturel'), ('Détente', 'Détente'), ('Sportif', 'Sportif'), ('Omra', 'Omra'), ('Haj', 'Haj')], default='Aventure', max_length=20),
        ),
    ]
