# Generated by Django 5.0 on 2024-01-14 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_activite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offrevoyage',
            name='activite_prevue',
        ),
        migrations.AddField(
            model_name='activite',
            name='offre_voyage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='blog.offrevoyage'),
        ),
    ]
