# Generated by Django 5.0 on 2024-01-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_offrevoyage_activite_prevue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='prix_initial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
