# Generated by Django 5.0 on 2024-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_activite_prix_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='prix_promo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
